### ISSUE TITLE
how to change the register form?

### ISSUE THREAD

**Issue by epljl** [stefanvanherwijnen/quasar-app-extension-http-authentication#21]
for example, i want to add some edit compoment to the reg form, how can i do it?

thanks.

**Comment by stefanvanherwijnen** [comment]
Have a look at https://github.com/stefanvanherwijnen/quasar-app-extension-http-authentication/issues/9

**Comment by stefanvanherwijnen** [comment]
Should be fixed or no longer applicable in v2.
