### ISSUE TITLE
the login response is not defined

### ISSUE THREAD

**Issue by epljl** [stefanvanherwijnen/quasar-app-extension-http-authentication#22]
where i input correct username and password in login page, in the web debugger, i can see the backend has send the token to me.

but the test app did not go to the home page.

 onSubmit () {
      this.loading = true
      this.$auth
        .login(this.data)
        .then(response => {
          this.$router.replace('/')
          this.$store.dispatch('auth/loginCallback')
        })

when i debug, it shows the response has not defined. why?

**Comment by stefanvanherwijnen** [comment]
Check if the request returns an error.

```
.catch(err => console.log(err))
```

**Comment by epljl** [comment]
here is my code and error

![QQ图片20200913000737](https://user-images.githubusercontent.com/70857465/92999644-2f21f000-f555-11ea-9777-182271bb5e61.png)

![22222222222222](https://user-images.githubusercontent.com/70857465/92999670-62647f00-f555-11ea-950a-011fb775a763.png)

![33333333333](https://user-images.githubusercontent.com/70857465/92999694-993a9500-f555-11ea-8c40-45c19ff155b4.png)

**Comment by stefanvanherwijnen** [comment]
You have not defined `response` in your `.then()` function. Try `.then(response => console.log(response))`

**Comment by stefanvanherwijnen** [comment]
Should be fixed or no longer applicable in v2.
