### ISSUE TITLE
How to use the components

### ISSUE THREAD

**Issue by jimtaylor123** [stefanvanherwijnen/quasar-app-extension-http-authentication#23]
Ok, after running the command `quasar ext add http-authentication` I was expecting the components to be copied in to my main src folder, but instead I can see them in the node_modules example only. Am I supposed to copy and paste all this into duplicate components in my app? This seems a bit odd, I would have expected it to be automatically placed in my main src directory.

**Comment by stefanvanherwijnen** [comment]
You don't have to copy them. They are symlinked in the routes. You can overwrite the default pages by adding your own routes to your custom pages.

The reason for this is that an AE update would overwrite your custom components if you are not careful. Also, when developing it is quite a hassle to rerender the components into the project on each change.

I'll try to find a better solution however, as it is confusing to most people.

**Comment by jimtaylor123** [comment]
Thanks, that helps a lot. But I think you're right, unless you spend a bit of time reading all the code it is confusing. Thanks for working on this package!
