### ISSUE TITLE
Install not working?

### ISSUE THREAD

**Issue by Daemach** [stefanvanherwijnen/quasar-app-extension-http-authentication#24]
I tried installing this extension in an app I'm working on but it didn't show up.  So I quasar create a brand new app to test extension installation.  https://www.screencast.com/t/fq6S9j8Pv8o  

After running quasar dev and trying to navigate to /auth/login there is nothing.  No pages in the components folder either.  https://www.screencast.com/t/McciFsJsjj  What am I doing wrong?

**Comment by stefanvanherwijnen** [comment]
I think the route is `/login`. Also, have a look at the previous issue.

**Comment by Daemach** [comment]
I m new to quasar and I was looking a quasar-extensions.json.  I see that the login page code is in node modules.  But I want to customize the layout and form to look like this:  [https://www.screencast.com/t/v9bhK715BDW](https://www.screencast.com/t/v9bhK715BDW)  How do I move all of this into my app?  Or is there another way to modify the style?

```
{
  "http-authentication": {
    "baseUrl": "http://localhost:420",
    "authenticationScheme": "Bearer",
    "identifierField": "email",
    "registerRoute": "/auth/register",
    "verificationRoute": "/auth/verify",
    "loginRoute": "/auth/login",
    "passwordForgotRoute": "/auth/password/forgot",
    "passwordResetRoute": "/auth/password/reset",
    "fetchUserRoute": "/auth/user"
  }
}
```

**Comment by stefanvanherwijnen** [comment]
Check https://github.com/stefanvanherwijnen/quasar-app-extension-http-authentication/issues/9

**Comment by Daemach** [comment]
Thank you.  FWIW, a FAQ might be helpful.  This one especially seems like a pretty common request and I hate to bother you.  Thanks for making this available.

**Comment by stefanvanherwijnen** [comment]
Should be fixed or no longer applicable in v2.
