### ISSUE TITLE
New variable - root object

### ISSUE THREAD

**Issue by Daemach** [stefanvanherwijnen/quasar-app-extension-http-authentication#25]
I use coldbox as a backend.  It's extremely fast, portable and used by NASA, among other large government agencies and corporations.  Its response object includes pagination support, error messaging and other information in addition to the root data return.  As such, the root node for the data itself is called "data" as in , response.data.data   Because of this, it would be useful to define another variable during setup that defines the "data" node within a return object. 

More info here:  https://www.screencast.com/t/Zxg8eRgO

**Comment by stefanvanherwijnen** [comment]
If I understand it correctly, check https://github.com/stefanvanherwijnen/quasar-app-extension-http-authentication/issues/16

**Comment by Daemach** [comment]
It's close, but this is actually a case of what the server itself is
returning.  The login action is looking for a data block in response.data,
but the server is returning response.data.data.

**Comment by stefanvanherwijnen** [comment]
Hmm, so this line causes the problem?
https://github.com/stefanvanherwijnen/quasar-app-extension-http-authentication/blob/90ae7b2d073c8b1d40473681234bf60a3148f51c/src/components/store/actions.js#L24

You're right that it shouldn't be hardcoded. I'll fix it in the next major update.

**Comment by Daemach** [comment]
Correct.  Also this line:
https://github.com/stefanvanherwijnen/quasar-app-extension-http-authentication/blob/90ae7b2d073c8b1d40473681234bf60a3148f51c/src/components/store/actions.js#L32

If you prompt for the root data node in a server response during
installation then stored that in RESPONSE_DATA_NODE you could do the
following:

const responseData = ( RESPONSE_DATA_NODE === '' ) ? response.data :
response.data[RESPONSE_DATA_NODE];  Then state.commit('setUser',
responseData.user.data),  const token = responseData.token would do it.

**Comment by stefanvanherwijnen** [comment]
Should be fixed or no longer applicable in v2.
