### ISSUE TITLE
Where do I store guarded routes?

### ISSUE THREAD

**Issue by Daemach** [stefanvanherwijnen/quasar-app-extension-http-authentication#26]
I want all routes to be guarded.  How do I set that up?  Or a single route?

I also want to force a login if they hit a secured url on the server and the server doesn't think they are logged in.  Where is that handled?  Auth should always be done on both the client and server sides.

**Comment by stefanvanherwijnen** [comment]
Add 'meta'` key on the route you want to have guarded see https://github.com/stefanvanherwijnen/quasar-app-extension-http-authentication/blob/master/test/app/src/router/routes.ts

**Comment by Daemach** [comment]
I want everything on this site to be guarded.  I added the meta key to "/"
and now the login page doesn't go anywhere.  The login itself works, but it
keeps coming back to the login screen.  Do I have to do something else
somewhere else?  If I remove that route and login, it drops me back to "/"
as I would expect it to.

**Comment by stefanvanherwijnen** [comment]
It behaves as expected. Your whole site is guarded, including your login page so only users which are logged in can access it. Instead you should add it on all child routes.

**Comment by stefanvanherwijnen** [comment]
Should be fixed or no longer applicable in v2.
