### ISSUE TITLE
App Extension "http-authentication" has missing index script...

### ISSUE THREAD

**Issue by frwkl** [stefanvanherwijnen/quasar-app-extension-http-authentication#32]
Hello,
thanks for nice work.
After install your test/app, i got the following

 App · ⚠️  App Extension "http-authentication" has missing index script...

What index script is needed ?
I copied index.template.html to index.html, but i got the same error.
Please can you help me ?

**Comment by stefanvanherwijnen** [comment]
Perhaps you need to run `yarn install` first in the test app folder.
Easier is to just install the extension in a new project

**Comment by frwkl** [comment]
OK. Thank you very much. I will test it at the weekend.

**Comment by JokerMartini** [comment]
The solution here is to delete the node modules folder and then run yarn install. In most cases you shouldn't have the actual node modules included in a repo. The repo becomes huge at that point.

**Comment by stefanvanherwijnen** [comment]
I never noticed node modules is checked in... You are correct and it shouldn't be there. Will be fixed in v2.

**Comment by JokerMartini** [comment]
No worries. I've made this mistake myself before :) I noticed when I
downloaded it was almost 400mb :)

When is v2 coming out? Will that support vue3

**Comment by stefanvanherwijnen** [comment]
Should be fixed or no longer applicable in v2.
