### ISSUE TITLE
logout problem

### ISSUE THREAD

**Issue by k3341095** [stefanvanherwijnen/quasar-app-extension-http-authentication#42]
I am developing with quasar .
There seems to be a problem with logout
My APP is SPA method. I use JWT authentication.
login works successfully.
Cookies are deleted when logging out.
document.cookie = ""
user = null

However, if I make a request with axios .. as is.. the request goes in normally.
With an existing token.

The error request is returned only after the page is refreshed -> Normal (not logged in)

Is this normal behavior? Do I need to refresh the page after logout?

**Comment by stefanvanherwijnen** [comment]
Should be fixed or no longer applicable in v2.
