### ISSUE TITLE
Make boot file register quasar-ui-http-authentication optionally (v2)

### ISSUE THREAD

**Issue by webrsb** [stefanvanherwijnen/quasar-app-extension-http-authentication#46]
I don't need quasar-ui-http-authentication UI components and I use mine owns. Can you make it optionally? Thanks

https://github.com/stefanvanherwijnen/quasar-app-extension-http-authentication/blob/717f1b7d2c7543aa4e9f450673e179b2e8a8ad21/app-extension/src/index.ts#L13

**Comment by stefanvanherwijnen** [comment]
V2 won't have a boot file anymore. It will also contain basically only the ui components so there might be no point in using it in your case.

**Comment by webrsb** [comment]
It is what I want, thanks.
